import time

def send_and_sleep(text):
    lines = text.split('\n')
    total_lines = len(lines)

    for idx, line in enumerate(lines):
        if line.strip() == "":
            print("Sleep\"300\"")
            time.sleep(0.3)  # Sleep for 300 milliseconds

        else:
            words = line.split()
            for word_idx, word in enumerate(words):
                if len(word) <=0:
                    print(f"Send\"{word}\"")
                else:
                    formatted_word = ''.join([f"{{{char}}}" for char in word])
                    print(f"Send\"{formatted_word}\"")
                if word_idx < len(words) - 1 or idx < total_lines - 1:
                    print("Sleep\"300\"")
                time.sleep(0.3)  # Sleep for 300 milliseconds

input_text = """
Q    Y  E  6  3  1  3
F4  F 2 3 F E  F EQ  F 136
DW    E  W  2  3 2   7
D  2    7  D  Y  Q J 36
FYR    3  Y  7    2
FRYR    EA    1 U Y R  E 1 6
FRAYREDW    E  W  2  3 2   7
DW  Y    W E A1  U   W
QQ    Y  E  6Y  3  1E  3
F4F4  FF 22 33 FF EE  FF EQEQ  FF 136136
DWDW    E  W  2E  3 2 W  7
DD  2  W  7  D  YE  QJ J 36
FYRFYR    3  Y  73    2Y
FRYRFRYR    EAEA    11 UU YY RR  EE 11 66
FRAYREDWFRAYREDW    EE  WW  22  33 22   77
FRAYREDWFRAYREDW  YY    WW EE A1A1  UU   WW
FRARYEA1UFRARYEA1U    7   7657 7 6 5 7 6 5 6
FRARYEA1UFRARYEA1U4  3 4 3  4 3  3  2  1 U 2
FRARYEA1UFRARYEA1UEU2    JJJJJJJRY2   3   2
A1UA1UW14   5   4   RU   RU   RU
RY36         J W Q Y W U Y 1
U  1UYTU U Y T U Y T Y R 1 E
U2  6 4 3  3 4 3  1 U  1 U Y
U3  Y R E  E R E  Q J  Q J H
    HH QQ TT YY YY U Y E WQ EJ Y YF
YF  R E S6 D3 F1 E7 W7 5 2 5 S5 D F Q
J7             SGQSGQ  JJ RR
WW EE  EE FF EE FF  WW QQ JJ QQ FF QQ SS JJ
AFQAFQ   572577527575275 75275 75275 J QE QE JW HQ JJQQJJ HH
QQ FF SS   AA SS HH  EQ WJ QH JQHJ HF D
DJEDJ     DDJJWWEEYY     SSFFQQQQEEWR
JQEQJE     DDJJWW UU11 UU  WW UU  WW JJ
Q    Y  E  6  3  1  3
F4  F 2 3 F E  F EQ  F 136
DW    E  W  2  3 2   7
D  2    7  D  Y  Q J 36
FYRFYR    3  Y  73    2Y
FRYRFR    EAEA    11 UU YY RR  EE 11 66
FRAYREDWFAREDW    EE  WW  22  33 22   77
FRAYREDWFAEDW  YY    WW EE A1A1  UU   WW
FRARYEA1UQFAEAUQ    Y  E  6Y  3  1E  3
FRARAUYEF4FAAUEF4  FF 22 33 FF EE  FF EQEQ  FF 136136
RARAUYEFDWAAUEFDW    E  W  2E  3 2 W  7
RARAUYFEDAAUFED  2  W  7  D  YE  QJ J 36
RARAUFEYFYRAAUFEFYR    3  Y  73    2Y
RARAUFEFYRYRAAUFEFRYR    EAEA    11 UU YY RR  EE 11 66
ARAFFRYREAUYREDWAAFFREAUYREDW    EE  WW  22  33 22   77
ARAFFRYRAUYREEDWAAFFRAUYREEDW  YY    WW EE 11  UU   WW
ARAFFRRAUYREYE1UJQEAAFFRAUREYE1UE  3  E  J  U  E  T  5
ARAFFRRAUYREYE1UJQEAAFFRARY1UEUEE  3  E  J  U  E  T  5
ARAFFRRAUYRYE1UEHWRAAFFRARY1UEUEE  3  E  J  U  E  T  5
AAFFRRAUYRYE1UERDJWEAAFFRARY1UEUEE  3  E  J  U  E  T  5
AAFFRRAUYRY1UEREJQEAAFFRARY1UEUE1    1  Y  6  2  3
AAFFRRAUYRY1UEREJQEAAFFRARUEUE1Y1    1  Y  6  2  3
AAFFRRAUYRY1UREEHWRAAFFRARUEUE1Y1    1  Y  6  2  3
AAFFRAUYRY1UREERDJWEAAFFRARUEUE1Y1    1  Y
AAFFRAUYRY1UREREHQTUAAFFRARUEUE1YHQTU       HH  QTUQTU   QTUQTU   HH
AAFFRAYRY1UREREUQTUQTUHQTUAAFFRAREUE1YUQTUQTUHQTU   QTUQTU   11    11    HH
AAFFRAYRYUREREUQTUQTUQTUQTU1HQTUAAFFRAREUEYUQTUQTUQTUQTU1HQTU       HH  QTUQTU   QTUQTU   DD
AAFFRAYRYREREUUQTUQTUQTU1QTUQTUQTUDWTAAFFRAREEYUUQTUQTUQTU1QTUQTUQTUDWT   WTWT   HT1HT1    T1T1    SS
AAFFRAYRYREREUUQUQUQUQTUQTUQTUTWTTT1SQRYAAFFRAREEYUUQUQUQUQTUQTUQTUTWTTT1SQRY       SS  QRYQRY   QRYQRY   SS
RAAFFARYREREUUUQUQUQTUQTUQTUTWTTT1QRYQRYQYSJYAAFFAREEUUUQUQUQTUQTUQTUTWTTT1QRYQRYQRYSJRY   JYJY   WD1WD1    WD1WD1    HH
AAFFARYREREUUUQUQUQTUQTUQTUTTTTQRYQRYQRYJYJYW1HQTUAAFFAREEUUUQUQUQTUQTUQTUTTTTQRYQRYQRYJRYJYW1HQTU       HH  QTUQTU   QTUQTU   HQUHQU
AAFFARYREREUUUQUQUQTUQTUTTTTQRYQRYQRYJYJYW1QTUQTUQTUHQUAAFFAREEUUUQUQUQTUQTUTTTTQRYQRYQRYJRYJYW1QTUQTUQTUHQU       HH  QUQU   QUQU   JJ
"""

send_and_sleep(input_text)
